export const topics = [
  "a fun fact about nature",
  "a random historical event",
  "a cool space fact",
  "a weird but true animal behavior",
  "a programming or tech trivia",
  "a famous quote with a twist",
  "an interesting philosophical question",
  "a quirky piece of trivia about food",
  "a funny fact about movies",
  "a random mathematical concept",
  "a mind-blowing scientific discovery",
  "a tech innovation that changed the world",
  "a strange habit of famous people",
  "an ancient civilization's interesting tradition",
  "a fascinating piece of mythology from around the world",
  "a fun fact about space exploration",
  "a historical figure's odd quirk",
  "an interesting fact about the brain",
  "a cool animal adaptation",
  "a fun piece of pop culture trivia",
  "a fact about artificial intelligence",
  "an unexpected connection between two unrelated things",
  "an interesting fact about human evolution",
  "a bizarre scientific experiment",
  "an odd historical coincidence",
  "a unique language feature or word",
  "a mysterious unsolved event or case",
  "an underrated invention that changed life as we know it",
  "a fun fact about how things are made",
  "a crazy weather phenomenon",
  "an unexplained natural wonder",
  "a hidden gem in art history",
  "a quirky custom or tradition from around the world",
  "a technological breakthrough from the past",
  "a wild conspiracy theory that has some truth",
  "an animal's surprising intelligence",
  "a piece of trivia about famous landmarks",
  "a cool space mission that was almost forgotten",
  "a historical invention that failed spectacularly",
  "a sports fact that changed the game",
  "a forgotten chapter in the history of music",
  "a breakthrough moment in medicine",
  "a fascinating fact about human senses",
  "a wild scientific theory that's not proven yet",
  "a piece of wisdom from an ancient culture",
  "a fun fact about famous art pieces",
  "a mythological creature that sounds real",
  "a groundbreaking discovery that was accidental",
  "a super rare celestial event",
  "a little-known fact about time travel",
  "a cool historical artifact",
  "a peculiar natural phenomenon",
  "an amazing fact about the deep ocean",
  "a fact about how animals communicate",
  "a surprisingly useful skill you can learn",
  "an obscure hobby or interest",
  "a weird piece of scientific trivia",
  "a scientific paradox",
  "a piece of space trivia about a distant galaxy",
  "an interesting fact about the world's oldest tree",
  "an unusual plant that's used in medicine",
  "an unexpected connection between biology and technology",
  "a fun fact about how electricity works",
  "an interesting cultural festival from around the world",
  "a futuristic technology that's already here",
  "an odd but true superstition",
  "a curious fact about the internet's history",
  "a piece of trivia about the human body",
  "a fascinating fact about birds",
  "a strange pattern in nature that has scientists baffled",
  "a cool robotics breakthrough",
  "an incredible fact about the animal kingdom",
  "a random piece of art history",
  "an old invention that's still in use today",
  "a cool ancient technology",
  "a bizarre historical event involving food",
  "a philosophical theory that challenges your mind",
  "a quirky fact about early computer technology",
  "an interesting connection between art and mathematics",
  "a cool space-time concept",
  "a fact about the world's largest organism",
  "an odd fact about famous scientists",
  "a cool scientific application of math",
  "a strange artifact from ancient Egypt",
  "a fun historical fact about transportation",
  "an unexpected scientific discovery made by accident",
  "a random fun fact about animals in space",
  "a surprising discovery about human psychology",
  "a cool mystery that was recently solved",
  "an unusual historical fashion trend",
  "a fun fact about weather patterns",
  "a mind-blowing fact about the size of the universe",
  "an unexplained phenomenon in quantum physics",
  "a quirky discovery from paleontology",
  "an odd fact about famous books",
  "an interesting fact about underwater life",
  "a surprising fact about sound",
  "an unusual fact about the development of video games",
  "a fun fact about how our brain processes memories",
  "an interesting fact about the way we dream",
  "a weird historical figure",
  "a mind-blowing fact about the speed of light",
  "a fun fact about the chemistry behind everyday things",
  "a strange but true fact about the internet of things",
  "a weird medical case that's still being studied",
  "a cool fact about the origins of a popular tradition",
  "a unique aspect of a country's cultural heritage",
  "a fascinating fact about space travel",
  "an obscure fact about famous inventions",
  "a quirky tidbit from the history of fashion",
  "a fun fact about childhood development",
  "a surprising discovery about the ancient world",
  "an amazing fact about food and cooking",
  "a cool historical fact about exploration",
  "a quirky phenomenon in language evolution",
  "a strange fact about the world’s oceans",
  "an unbelievable but true fact about animals",
];

export const openings = [
  "OMG",
  "omg",
  "did you know that",
  "fun fact",
  "guess what",
  "random fact",
  "here's something cool",
  "have you heard",
  "true story",
  "mind blown",
  "fun fact alert",
  "did you know",
  "random thought",
  "check this out",
  "believe it or not",
  "here’s a crazy fact",
  "here's a little-known fact",
  "prepare to be amazed",
  "did you ever wonder",
  "you won't believe this",
  "here’s a gem",
  "ready for a wild fact?",
  "you'll love this one",
  "brace yourself for this",
  "what if I told you",
  "no way, but it's true",
  "this one’s a game-changer",
  "you've got to hear this",
  "here’s a shocking truth",
  "can you believe this?",
  "you might find this interesting",
  "wait for it...",
  "this will blow your mind",
  "check this gem out",
  "ever wondered about this?",
  "here’s something to blow your mind",
  "what I found might surprise you",
  "have you ever heard of this?",
  "this one will make you think",
  "thought you'd never know this",
  "wait i just found out that",
  "bruh no way",
  "this is wild",
  "woah",
  "this is insane",
  "this is crazy",
];
